{{ if .Values.ingress.createIngress }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: languagetool-ingress
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - "{{ .Values.extUrl }}"
      secretName: "{{ .Values.ingress.secretName }}"
  rules:
    - host: "{{ .Values.extUrl }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: languagetool-service
                port:
                  number: 80
...
{{ end }}